defmodule Mix.Tasks.Xcribe.Serve do
  @moduledoc """
  Serve the generated OpenAPI documentation with Swagger UI.

  ```sh
  mix xcribe.serve
  ```

  The document is not generated by this task, it is only served — run
  `mix xcribe.doc` first. The endpoint of the documented application is started
  so it can serve the document file itself, which means `file_path` and
  `file_name` must match one of its `Plug.Static` plugs. See `Xcribe.Config` for
  both keys and `Xcribe` for the whole configuration reference.

  The task serves the endpoint configured with `serve: true`. When more than one is,
  or to serve an endpoint that has serve mode disabled, name it:

  ```sh
  mix xcribe.serve -e YourAppWeb.Endpoint
  ```

  The port comes from the `:server_port` config key (default `4040`), and
  `:open_browser` opens the served documentation in your browser. Serving needs a
  web server in your dependencies, either Bandit or `Plug.Cowboy` — a Phoenix
  application already has one.

  Note: to use this task you must configure `preferred_envs: ["xcribe.serve": :test]`
  on your `mix.exs` file, so the task runs in the environment your Xcribe
  configuration lives in.
  """
  use Mix.Task

  alias Xcribe.{CLI.Output, Config}

  # The endpoint of the documented application is started by this task, so the
  # consumer's application must not be running already: `app.start` would boot
  # their endpoint on their own port and our supervised copy would fail with
  # `{:error, {:already_started, _pid}}`.
  @requirements ["app.config"]

  @shortdoc "Serve the generated Xcribe documentation"

  @doc false
  def run(opts), do: run_task(opts)

  @doc false
  def run_task(opts, server_function \\ &start_server/1, browser_function \\ &open_browser/1) do
    with {:ok, endpoint} <- fetch_endpoint(opts),
         config = serving_config(Config.fetch_config(endpoint)),
         {:ok, config} <- Config.check_configurations(config),
         {:ok, supervisor} <- start_web_server(config, server_function),
         {:ok, config} <- Config.check_configurations(config, [:served_document]) do
      serve(config, supervisor, browser_function)
    else
      {:error, errors} ->
        Output.print_configuration_errors(errors)

        Output.print_message("Xcribe Task - aborted", :error)

        exit({:shutdown, 1})
    end
  end

  defp serve(config, supervisor, browser_function) do
    reference = Process.monitor(supervisor)

    Output.print_message("Xcribe Task - serving documentation on #{document_url(config)}")

    open_documentation(config, browser_function)

    receive do
      {:DOWN, ^reference, :process, ^supervisor, reason} -> exit(reason)
    end
  end

  defp open_documentation(%{open_browser: true} = config, browser_function) do
    browser_function.(document_url(config))
  end

  defp open_documentation(_config, _browser_function), do: :ok

  defp serving_config(config), do: %{config | serve: true}

  defp document_url(config), do: "http://localhost:#{config.server_port}"

  defp start_web_server(config, server_function) do
    config
    |> server_function.()
    |> handle_server_start(config)
  end

  defp start_server(config) do
    config
    |> web_server_child()
    |> start_supervisor(config)
  end

  @server_message "Xcribe couldn't find a web server to serve the documentation with"
  @server_instructions "Add a web server to your dependencies, either Bandit or Plug.Cowboy"
  defp web_server_child(config) do
    plug = {Xcribe.Web.Plug, endpoint: config.endpoint, serving?: true, proxy?: true}

    cond do
      Code.ensure_loaded?(Bandit) ->
        {:ok, {Bandit, plug: plug, port: config.server_port}}

      Code.ensure_loaded?(Plug.Cowboy) ->
        {:ok, {Plug.Cowboy, scheme: :http, plug: plug, port: config.server_port}}

      true ->
        {:error, [{nil, nil, @server_message, @server_instructions}]}
    end
  end

  defp start_supervisor({:error, _errors} = error, _config), do: error

  defp start_supervisor({:ok, web_server}, config) do
    # Supervisor.start_link/2 links the supervisor to this process, so a child that
    # fails to start — a port already in use, most often — would kill the task with
    # a raw exit signal before its {:error, reason} could be reported as a
    # configuration error.
    Process.flag(:trap_exit, true)

    Supervisor.start_link([config.endpoint, web_server], strategy: :one_for_one)
  end

  defp handle_server_start({:ok, supervisor}, _config), do: {:ok, supervisor}

  defp handle_server_start({:error, [{_key, _value, _msg, _info} | _rest]} = error, _config) do
    error
  end

  defp handle_server_start({:error, reason}, config) do
    reason
    |> failure_kind()
    |> start_failure(reason, config)
  end

  # A supervisor wraps the reason of the child that failed in as many
  # {:failed_to_start_child, _, _} layers as there are levels between it and the
  # process that really failed, so the two failures worth their own advice are
  # recognized wherever they appear in the reason.
  defp failure_kind(reason) do
    inspected = inspect(reason, limit: :infinity)

    cond do
      String.contains?(inspected, ":eaddrinuse") -> :port_in_use
      String.contains?(inspected, ":already_started") -> :already_started
      true -> :unknown
    end
  end

  @port_message "Xcribe couldn't start the documentation server on the configured port"
  @port_instructions "Free the port or configure another one: `config :xcribe, Endpoint, server_port: 4041`"
  defp start_failure(:port_in_use, _reason, config) do
    {:error, [{:server_port, config.server_port, @port_message, @port_instructions}]}
  end

  @already_started_message "Xcribe couldn't start your Endpoint to serve the documentation because it is already running"
  @already_started_instructions "Run the task in an environment where your application is not started, `preferred_envs: [\"xcribe.serve\": :test]`, or stop the running instance first"
  defp start_failure(:already_started, _reason, _config) do
    {:error, [{nil, nil, @already_started_message, @already_started_instructions}]}
  end

  @start_message "Xcribe couldn't start the documentation server"
  defp start_failure(:unknown, reason, _config) do
    {:error, [{nil, nil, @start_message, "The supervisor reported #{inspect(reason)}"}]}
  end

  defp fetch_endpoint(opts) do
    opts
    |> OptionParser.parse_head(aliases: [e: :endpoint], strict: [endpoint: :string])
    |> elem(0)
    |> Keyword.get(:endpoint)
    |> find_endpoint(Config.all_endpoints())
  end

  defp find_endpoint(nil, endpoints) do
    endpoints
    |> Enum.filter(&serving?/1)
    |> Enum.sort()
    |> choose_endpoint()
  end

  defp find_endpoint(_given, []), do: choose_endpoint([])

  defp find_endpoint(given, endpoints) do
    case Enum.find(endpoints, &(inspect(&1) == given)) do
      nil -> unknown_endpoint_error(given, endpoints)
      endpoint -> {:ok, endpoint}
    end
  end

  defp serving?(endpoint), do: endpoint |> Config.fetch_config() |> Map.fetch!(:serve)

  @no_endpoint_message "Xcribe has no endpoint configured to serve documentation for"
  @no_endpoint_instructions ~s(Enable serve mode for the endpoint you want to read the documentation of: `config :xcribe, YourAppWeb.Endpoint, serve: true, file_path: {"priv/static", "api"}`, and run the task in that environment with `preferred_envs: ["xcribe.serve": :test]`)
  defp choose_endpoint([]) do
    {:error, [{nil, nil, @no_endpoint_message, @no_endpoint_instructions}]}
  end

  defp choose_endpoint([endpoint]), do: {:ok, endpoint}

  @many_endpoints_message "More than one endpoint is configured to serve documentation, so Xcribe can't tell which one you mean"
  defp choose_endpoint(endpoints) do
    instructions =
      "Name the endpoint you want: `mix xcribe.serve -e #{endpoints |> List.first() |> inspect()}`. Configured to serve: #{Enum.map_join(endpoints, ", ", &inspect/1)}"

    {:error, [{nil, nil, @many_endpoints_message, instructions}]}
  end

  @unknown_endpoint_message "Xcribe has no configuration for the given endpoint"
  defp unknown_endpoint_error(given, endpoints) do
    instructions =
      "Configure it with `config :xcribe, #{given}, serve: true` or name one of the configured endpoints: #{endpoints |> Enum.sort() |> Enum.map_join(", ", &inspect/1)}"

    {:error, [{:endpoint, given, @unknown_endpoint_message, instructions}]}
  end

  defp open_browser(url) do
    {command, args} =
      case :os.type() do
        {:win32, _any} -> {"cmd", ["/c", "start", url]}
        {:unix, :darwin} -> {"open", [url]}
        {:unix, _any} -> {"xdg-open", [url]}
      end

    System.cmd(command, args)
  end
end
